### ISSUE TITLE
Problems with parallel

### ISSUE THREAD

**Issue by AlessandroPilli** [SchwartzLab/mazter_mine#10]
Dear Miguel,

I'm currently in the pre-processing of my data via the mazter_mine.R script and I encountered an error that is related to a parallel process but I don't understand what I should do to solve it, can you help me out? 

the specific error is:

Error in checkForRemoteErrors(val) : 
  2 nodes produced errors; first error: missing value where TRUE/FALSE needed
Calls: %>% ... clusterApply -> staticClusterApply -> checkForRemoteErrors

this is happening for every one of the 6 files (.Rdata) I'm giving in input.

Sincerely
Alessandro

**Comment by AngelCampos** [comment]
Hello Alessandro.
Please try troubleshooting your issue with these two options:
1. Run the pipeline into a subset of genes in your BED annotation. If it works then you may be able to spot the genes in which it fails and the reason. Sometimes there are missanotated genes e.g. out of the chromosomes.
2. Run the scripts with only one core. The error message then should be more informative.

Let me know how it goes.
Best

**Comment by AlessandroPilli** [comment]
I fixed the problem, the gene names caused it. In my geneAnnot.bed the gene names were of the type NM_XXXXXXXX and not the UCSC ones as in the tutorial, and in the mazter_mine.R script when reaching the step # All Sites motif distance, it was removing the gene name at the underscore leaving only NM as gene name for every gene and so blocking the following steps.

thank you
Alessandro
