### ISSUE TITLE
Why 3' end cleavage efficiency is much lower than the 5' end's?

### ISSUE THREAD

**Issue by ssun1116** [SchwartzLab/mazter_mine#9]
Dear Mazter_mine Team

Hello, I'm analyzing reads fragmented with mazF using this mazter_mine pipeline. 
Thank you for developing such a convenient and wonderful tool!

I'm analyzing multiple reads sequenced by small RNA-seq kits and strand-awareness RNA-seq kits, but unfortunately, we encountered a problem that the cleavage efficiency at the 3' end always seemed much lower than the efficiency of 5' end regardless of the sequencing kit.
Several trimming options have been tried to improve quality, but the results have not been significantly improved.
I wonder why the 3' end efficiency is much lower than the 5' end read, can you give me some advice on this issue?

Sincerely,
Seoyeon Kim
[trimmed.U2OS2.DMSO_output_0718Aligned.out.Rdata_MASTER-seq_QC.pdf](https://github.com/SchwartzLab/mazter_mine/files/9148969/trimmed.U2OS2.DMSO_output_0718Aligned.out.Rdata_MASTER-seq_QC.pdf)

**Comment by AngelCampos** [comment]
Hello Seoyeon.

Indeed the signal looks messed up, there seems to be no correlation between
3' cleavage efficiencies and 5' cleavage efficiencies.
Usually, the correlation is already high at ~15-20 bp distance to other ACA
sites and it further increases as we consider sites farther away from each
other, until it stagnates around ~60 bp away in some of our experiments
(depending on mean insert size).

If you are not able to reproduce the experimental conditions that we used
perhaps explaining them in detail to the co-author in charge of the
experimental side of the project can throw some light on what is wrong.
Her name is Sarit Edelheit, email: ***@***.***

Another option would be to consider only the cleavage efficiency from
either 5' or 3' side if the cleavage efficiency is indeed coherent
with previously annotated sites or previously measured MS (or another
method like SCARLET) m6A stoichiometries.

Hope this info helps you Seoyeon.

Best and good luck.


*Miguel Angel García Campos, Ph.D.*

Website <https://angelcampos.github.io/> | Twitter
<https://twitter.com/GarciaCamposM> | GScholar
<https://scholar.google.com/citations?user=-J7nzzcAAAAJ&hl> | Instagram
<https://www.instagram.com/garciacampos_m/>

Postdoc fellow at the SchwartzLab
<https://www.weizmann.ac.il/molgen/Schwartz/>, Molecular Genetics
Department, Weizmann Institute of Science.
